# Generated by Django 5.0 on 2023-12-26 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remain', '0002_alter_task_remainder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='remainder_time',
            field=models.TimeField(),
        ),
    ]
