# Generated by Django 5.0 on 2023-12-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remain', '0003_task_remainder_date_alter_task_remainder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
