# Generated by Django 5.0 on 2023-12-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remain', '0004_alter_task_remainder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remainder_date',
            field=models.DateField(),
        ),
    ]
