# Generated by Django 5.0 on 2023-12-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remain', '0006_alter_task_remainder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
